# Generated by Django 2.2 on 2020-04-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_auto_20200428_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
